[package]
name = "web-flash"
version = "0.1.1"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.2"
espflash = "2.0.0-rc.1"
esp-idf-part = "0.1.1"
clap = { version = "3.1.18", features=["env", "derive"] }
opener = "0.5.0"
anyhow = "1.0.57"
xmas-elf = "0.8.0"
